services:
  - type: web
    name: allodocteur-api
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: API_KEY
        sync: false
      - key: ALLODOCTEUR_KB_PATH
        value: data/kb_allodocteur_v3_complete.json
      - key: ENABLE_REQUEST_LOGS
        value: true
      - key: LOG_DIR
        value: logs
      - key: CORS_ORIGINS
        value: "*"
